# -*- coding: utf-8 -*-
"""DadosEficienciaGeracao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tP7h60-9cbagSuUdkwk25CKDwxNg7yWF
"""

# ==========================================================
# 🔧 ETAPA 1 — Instalação e configuração inicial do PySpark
# ==========================================================
!apt-get install openjdk-11-jdk-headless -qq > /dev/null
!pip install pyspark==3.5.1 -q

from pyspark.sql import SparkSession
from pyspark.sql.functions import (
    col, regexp_replace, trim, upper, to_date, year, month,
    when, countDistinct, avg, sum as _sum, round
)

spark = SparkSession.builder.master("local[*]").appName("Tratamento ANEEL").getOrCreate()

# ==========================================================
# 🔧 ETAPA 2 — Leitura dos arquivos CSV
# ==========================================================
path1 = "/content/drive/MyDrive/Projeto_ELE_ECO/aneel-empreendi-geracao1.csv"
path2 = "/content/drive/MyDrive/Projeto_ELE_ECO/aneel-empreendi-geracaodiario.csv"

# Lê ambos os arquivos
df1 = spark.read.csv(path1, header=True, sep=";", encoding="latin1")
df2 = spark.read.csv(path2, header=True, sep=";", encoding="latin1")

# Une os dois conjuntos (caso tenham a mesma estrutura)
df = df1.unionByName(df2)

print(f"Total de linhas combinadas: {df.count():,}")

# ==========================================================
# 🔧 ETAPA 3 — Limpeza e padronização das colunas
# ==========================================================

# Remove espaços e deixa colunas em formato consistente
df = df.select([trim(col(c)).alias(c.strip()) for c in df.columns])

# Corrige colunas numéricas (trocando vírgula por ponto e convertendo para double)
num_cols = [
    "MdaPotenciaOutorgadaKw",
    "MdaPotenciaFiscalizadaKw",
    "MdaGarantiaFisicaKw"
]

for c in num_cols:
    df = df.withColumn(c, regexp_replace(col(c), ",", ".").cast("double"))

# Converte datas
df = df.withColumn("DatEntradaOperacao", to_date("DatEntradaOperacao"))
df = df.withColumn("DatGeracaoConjuntoDados", to_date("DatGeracaoConjuntoDados"))

# Cria colunas de ano e mês
df = df.withColumn("ano", year("DatGeracaoConjuntoDados"))
df = df.withColumn("mes", month("DatGeracaoConjuntoDados"))

# ==========================================================
# 🔧 ETAPA 4 — Criação de colunas derivadas e métricas
# ==========================================================

# Calcula eficiência: potência fiscalizada / potência outorgada
df = df.withColumn(
    "eficiencia_percent",
    when(col("MdaPotenciaOutorgadaKw") > 0,
         round((col("MdaPotenciaFiscalizadaKw") / col("MdaPotenciaOutorgadaKw")) * 100, 2))
    .otherwise(None)
)

# ==========================================================
# 🔧 ETAPA 5 — Agregações por UF, tipo de geração e mês
# ==========================================================

df_agregado = (
    df.groupBy("ano", "mes", "SigUFPrincipal", "SigTipoGeracao")
      .agg(
          countDistinct("NomEmpreendimento").alias("num_empreendimentos"),
          round(avg("MdaPotenciaOutorgadaKw"), 2).alias("pot_media_outorgada_kw"),
          round(avg("MdaPotenciaFiscalizadaKw"), 2).alias("pot_media_fiscalizada_kw"),
          round(avg("eficiencia_percent"), 2).alias("eficiencia_media_percent"),
          round(_sum("MdaPotenciaOutorgadaKw"), 2).alias("pot_total_outorgada_kw"),
          round(_sum("MdaPotenciaFiscalizadaKw"), 2).alias("pot_total_fiscalizada_kw")
      )
      .orderBy("ano", "mes", "SigUFPrincipal", "SigTipoGeracao")
)

# ==========================================================
# 🔧 ETAPA 6 — Estatísticas descritivas (opcional)
# ==========================================================
df_agregado.describe().show(truncate=False)

# ==========================================================
# 🔧 ETAPA 7 — Exportação final para CSV (Looker Studio)
# ==========================================================
output_path = "/content/energia_tratada_aneel.csv"
df_agregado.coalesce(1).write.option("header", True).mode("overwrite").csv(output_path)

print(f"\n✅ Arquivo tratado salvo em: {output_path}")
print("Pronto para importar no Looker Studio!")